"""Update money type

Revision ID: af51555ce3d1
Revises: f6a2eda07ea1
Create Date: 2026-07-29 14:15:33.479353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af51555ce3d1'
down_revision: Union[str, Sequence[str], None] = 'f6a2eda07ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_product_id'), table_name='attachment')
    op.drop_index(op.f('ix_category_product_category_id'), table_name='category_product')
    op.drop_index(op.f('ix_category_product_product_id'), table_name='category_product')
    op.drop_index(op.f('ix_order_client_id'), table_name='order')
    op.drop_index(op.f('ix_order_manager_id'), table_name='order')
    op.drop_index(op.f('ix_order_shipping_id'), table_name='order')
    op.drop_index(op.f('ix_order_status_id'), table_name='order')
    op.drop_index(op.f('ix_order_product_order_id'), table_name='order_product')
    op.drop_index(op.f('ix_order_product_product_id'), table_name='order_product')
    op.drop_index(op.f('ix_postoffice_type_id'), table_name='postoffice')
    op.drop_index(op.f('ix_shipping_payment_type_id'), table_name='shipping')
    op.drop_index(op.f('ix_shipping_postoffice_id'), table_name='shipping')
    op.drop_index(op.f('ix_specification_product_product_id'), table_name='specification_product')
    op.drop_index(op.f('ix_specification_product_specification_id'), table_name='specification_product')
    op.drop_index(op.f('ix_user_role_id'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_role_id'), 'user', ['role_id'], unique=False)
    op.create_index(op.f('ix_specification_product_specification_id'), 'specification_product', ['specification_id'], unique=False)
    op.create_index(op.f('ix_specification_product_product_id'), 'specification_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipping_postoffice_id'), 'shipping', ['postoffice_id'], unique=False)
    op.create_index(op.f('ix_shipping_payment_type_id'), 'shipping', ['payment_type_id'], unique=False)
    op.create_index(op.f('ix_postoffice_type_id'), 'postoffice', ['type_id'], unique=False)
    op.create_index(op.f('ix_order_product_product_id'), 'order_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_product_order_id'), 'order_product', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_id'), 'order', ['status_id'], unique=False)
    op.create_index(op.f('ix_order_shipping_id'), 'order', ['shipping_id'], unique=False)
    op.create_index(op.f('ix_order_manager_id'), 'order', ['manager_id'], unique=False)
    op.create_index(op.f('ix_order_client_id'), 'order', ['client_id'], unique=False)
    op.create_index(op.f('ix_category_product_product_id'), 'category_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_category_product_category_id'), 'category_product', ['category_id'], unique=False)
    op.create_index(op.f('ix_attachment_product_id'), 'attachment', ['product_id'], unique=False)
    # ### end Alembic commands ###
