"""add slug to category model

Revision ID: ce5f6b596b90
Revises: 1b2901bfdf57
Create Date: 2026-08-17 13:08:30.636561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5f6b596b90'
down_revision: Union[str, Sequence[str], None] = '1b2901bfdf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'category', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
