"""Add init models

Revision ID: f6a2eda07ea1
Revises: 
Create Date: 2026-07-29 13:57:00.102841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a2eda07ea1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postoffice_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.CheckConstraint('discount >= 0 AND discount <= 100', name='ck_product_discount'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_filter', sa.Boolean(), nullable=False),
    sa.Column('filter_key', sa.String(length=255), nullable=False),
    sa.Column('filter_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_product',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'product_id')
    )
    op.create_table('postoffice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['postoffice_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specification_product',
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], ),
    sa.PrimaryKeyConstraint('specification_id', 'product_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('payment_type_id', sa.Integer(), nullable=False),
    sa.Column('postoffice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], ),
    sa.ForeignKeyConstraint(['postoffice_id'], ['postoffice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('shipping_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_price', sa.DECIMAL(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shipping_id'], ['shipping.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_product')
    )
    # ### end Alembic commands ###

    # FK indexes
    op.create_index('ix_attachment_product_id', 'attachment', ['product_id'])
    op.create_index('ix_category_product_category_id', 'category_product', ['category_id'])
    op.create_index('ix_category_product_product_id', 'category_product', ['product_id'])
    op.create_index('ix_specification_product_specification_id', 'specification_product', ['specification_id'])
    op.create_index('ix_specification_product_product_id', 'specification_product', ['product_id'])
    op.create_index('ix_postoffice_type_id', 'postoffice', ['type_id'])
    op.create_index('ix_shipping_payment_type_id', 'shipping', ['payment_type_id'])
    op.create_index('ix_shipping_postoffice_id', 'shipping', ['postoffice_id'])
    op.create_index('ix_user_role_id', 'user', ['role_id'])
    op.create_index('ix_order_status_id', 'order', ['status_id'])
    op.create_index('ix_order_client_id', 'order', ['client_id'])
    op.create_index('ix_order_manager_id', 'order', ['manager_id'])
    op.create_index('ix_order_shipping_id', 'order', ['shipping_id'])
    op.create_index('ix_order_product_product_id', 'order_product', ['product_id'])
    op.create_index('ix_order_product_order_id', 'order_product', ['order_id'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    op.drop_table('order')
    op.drop_table('shipping')
    op.drop_table('user')
    op.drop_table('specification_product')
    op.drop_table('postoffice')
    op.drop_table('category_product')
    op.drop_table('attachment')
    op.drop_table('specification')
    op.drop_table('role')
    op.drop_table('product')
    op.drop_table('postoffice_type')
    op.drop_table('payment_type')
    op.drop_table('order_status')
    op.drop_table('category')
    # ### end Alembic commands ###

    op.drop_index('ix_order_product_order_id', table_name='order_product')
    op.drop_index('ix_order_product_product_id', table_name='order_product')
    op.drop_index('ix_order_shipping_id', table_name='order')
    op.drop_index('ix_order_manager_id', table_name='order')
    op.drop_index('ix_order_client_id', table_name='order')
    op.drop_index('ix_order_status_id', table_name='order')
    op.drop_index('ix_user_role_id', table_name='user')
    op.drop_index('ix_shipping_postoffice_id', table_name='shipping')
    op.drop_index('ix_shipping_payment_type_id', table_name='shipping')
    op.drop_index('ix_postoffice_type_id', table_name='postoffice')
    op.drop_index('ix_specification_product_product_id', table_name='specification_product')
    op.drop_index('ix_specification_product_specification_id', table_name='specification_product')
    op.drop_index('ix_category_product_product_id', table_name='category_product')
    op.drop_index('ix_category_product_category_id', table_name='category_product')
    op.drop_index('ix_attachment_product_id', table_name='attachment')
